<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DfE.EducationProviderRegistry.Web.MVC.UITests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Selenium.Support" />
	<PackageReference Include="Selenium.WebDriver" />
	<PackageReference Include="Xunit.DependencyInjection" />
	<PackageReference Include="Xunit.DependencyInjection.Logging" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DfE.EducationProviderRegistry.Web.SharedTests\DfE.EducationProviderRegistry.Web.SharedTests.csproj" />
    <ProjectReference Include="..\DfE.WebDriver\DfE.WebDriver.csproj" />
  </ItemGroup>

</Project>
