<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="DfE.Core.Libraries.IntegrationTests" />
	<PackageReference Include="DfE.Core.Libraries.IntegrationTests.Database.Postgres" />
	<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
