<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.msbuild">
	  <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="DfE.Core.Libraries.IntegrationTests.Database.Postgres" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
	<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	<PackageReference Include="xunit.v3.mtp-v2" />
	<PackageReference Include="Xunit.DependencyInjection" />
	<PackageReference Include="Xunit.DependencyInjection.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DfE.EducationProviderRegistry.Web.SharedTests\DfE.EducationProviderRegistry.Web.SharedTests.csproj" />
  </ItemGroup>

</Project>
